### ISSUE TITLE
Loot Problem

### ISSUE THREAD

**Issue by ynnniV** [docc5m/nx_hunting#3]
There is something strange with the loot too.
The animals spawn is a good way. But when you kill them there is something strange like giving the item of other animals.

I've added like 8 animals with alot of items, and for example a coyote giving me something of the deer.

Into the config is all good.

**Comment by ynnniV** [comment]
Seems a timer problem.
When there is too much animals in a low timing it will have problem. Just take a look.
I solved this one by making more seconds to spawn.

**Comment by ynnniV** [comment]
Just saw it with more calm and the script recognize the only **LAST** animalID spawning.

So if he spawn a coyote but after sometime spawn a deer, if you will kill the coyote he will give you the deer items.

There is a screenshot:

![image](https://github.com/docc5m/nx_hunting/assets/9847632/af4ac68c-16f4-4e99-ae1a-f6a25f0e2c98)

The first 3 print are about the last animal spawned, but i killed an a_c_boar and he gived me the deer items as you can see.

**Comment by nextscripts-5m** [comment]
Thanks, i will see. This was a resource posted and never tested for real. Now i have testers 😎

**Comment by ynnniV** [comment]
> Thanks, i will see. This was a resource posted and never tested for real. Now i have testers 😎

Happy about that! 👍 

The problem, anyway, is when animalID get updated in spawnAnimals.
Right now is on a loop and when a animal spawn it change always and when u try to complete the loot on the function complete he's calling the animalID of the last one spawned. 

The script is good anyway, just that problem ruin! But for the rest of the things, i think is super good 🥇

**Comment by nextscripts-5m** [comment]
> Right now is on a loop and when a animal spawn it change always and when u try to complete the loot on the function complete he's calling the animalID of the last one spawned.

Yes, I understand the problem and I already have the idea on how to fix it.

Just for asking, are you able to script? If yes, i'm searching people to work with 💯 Join my [discord](https://discord.gg/VU9Vhyhe7b)

**Comment by nextscripts-5m** [comment]
I've fixed with latest [release](https://github.com/docc5m/nx_hunting/releases/tag/v2.1)! 😄
