### ISSUE TITLE
isInArea while

### ISSUE THREAD

**Issue by ynnniV** [docc5m/nx_hunting#4]
I found another bug.
On the local spawnAnimals there is something strange with the _isInArea_.
It work and show true or false but the animals start to spawn anyway out of the zone.

**How to replicate this bug?**
Just enter for the 1st time on the zone, then exit and the script will say to you: you're out of the zone.
After some seconds the animals starts to spawn anyway.

I tried to download a fresh version of the script and i got the same bug.

**Comment by nextscripts-5m** [comment]
I see, that happens because when you enter the zone it starts a thread that run asynchronous and is Waiting so `isInArea` become false but the thread is already in the loop (_true condition_).

I've added a new line that avoid this :D
